security:
<<<<<<< HEAD
  jwt-secret: ${SECURITY_JWT-SECRET:default-unsafe-value}
=======
  jwt-secret: ${JWT_SECRET}

spring:
  security:
    user:
      name: none
      password: none
>>>>>>> develop
