
services:
  mysql:
    image: mysql:8.0
    container_name: ranking-service-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=!Gaptunklas7
      - MYSQL_DATABASE=dinetime_ranking_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.0
    command: ["redis-server", "/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/redis.conf  
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      timeout: 3s

  ranking-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_started
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/dinetime_ranking_db?allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=!Gaptunklas7
    ports:
      - "8080:8080"
      - "5005:5005"

volumes:
  redis-data:
  mysql-data:
