version: "3.8"

services:
  ranking-service:
    build:
      context: ./services/ranking-service
      args:
        - JAR_FILE=build/libs/ranking-service-0.0.1-SNAPSHOT.jar
    container_name: ranking-service
    environment:
      - NODE_ENV=production
    depends_on:
      ranking-mysql:
        condition: service_started
    networks:
      - dinetime-net


  ranking-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=!Gaptunklas7
      - MYSQL_DATABASE=dinetime_ranking_db
    ports:
      - "3306:3306"
    volumes:
      - ranking-mysql-data:/var/lib/mysql
    networks:
       - dinetime-net


  realtime-service:
    build:
      context: ./services/realtime-service
      target: prod              
    container_name: realtime-service
    environment:
      - NODE_ENV=production
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis
    networks:
      - dinetime-net

  
  matchmaker-service:
    build:
      context: ./services/matchmaker-service
      args:
        - JAR_FILE=build/libs/matchmaker-0.0.1-SNAPSHOT.jar
    container_name: matchmaker-service
    networks:
       - dinetime-net

  matchmaker-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=!Gaptunklas7
      - MYSQL_DATABASE=dinetime_matchmaker_db
    ports:
      - "3307:3306"
    volumes:
      - matchmaker-mysql-data:/var/lib/mysql
    networks:
       - dinetime-net

  identity-service:
    build:
      context: ./services/identity-service
      args:
        - JAR_FILE=build/libs/identity-service-0.0.1-SNAPSHOT.jar
    container_name: identity-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SECURITY_JWT-SECRET=${JWT_SECRET}
    ports:
      - "8082:8080"
    networks:
      - dinetime-net



  nginx-gateway:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - matchmaker-service
      - ranking-service
      - realtime-service
    networks:
      - dinetime-net


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - dinetime-net

  redis-test:
    image: redis:latest
    container_name: redis-test
    ports:
      - "6380:6379" 
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data:
  ranking-mysql-data:
  matchmaker-mysql-data:  

networks:
  dinetime-net:
    driver: bridge



