version: "3.8"

services:
  ranking-service:
    build:
      context: ./services/ranking-service
      args:
        - JAR_FILE=build/libs/ranking-service-0.0.1-SNAPSHOT.jar
    container_name: ranking-service
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    depends_on:
      ranking-mysql:
        condition: service_started


  ranking-mysql:
    image: mysql:8.0
    container_name: ranking-service-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=!Gaptunklas7
      - MYSQL_DATABASE=dinetime_ranking_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  realtime-service:
    build:
      context: ./services/realtime-service
      target: prod              
    container_name: realtime-service
    ports:
      - "5002:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  
  matchmaker-service:
    build: 
      context: ./services/matchmaker-service
    container_name: matchmaker-service
    ports:
      - "8000:8000"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  redis-test:
    image: redis:latest
    container_name: redis-test
    ports:
      - "6380:6379" 
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data:
  mysql-data:
