spring:
  application:
    name: matchmaker
  datasource:
    url: jdbc:mysql://localhost:3307/dinetime_matchmaker_db
    username: root
    password: "!Gaptunklas7"


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
