apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matchmaker-ingress
  annotations:
    appgw.ingress.kubernetes.io/health-probe-path: /matchmaker/healthz
spec:
  ingressClassName: azure-application-gateway
  rules:
    - http:
        paths:
          - path: /matchmaker
            pathType: Prefix
            backend:
              service:
                name: matchmaker-service
                port:
                  number: 80