apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaker-service
  labels:
    app: matchmaker-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmaker-service
  template:
    metadata:
      labels:
        app: matchmaker-service
    spec:
      containers:
        - name: matchmaker-service
          image: dinetimeacr.azurecr.io/dinetime-backend-matchmaker-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://matchmaker-mysql:3306/dinetime_matchmaker_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
