apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-service
  labels:
    app: realtime-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: realtime-service
  template:
    metadata:
      labels:
        app: realtime-service
    spec:
      containers:
        - name: realtime-service
          image: docker.io/dockerjarnodijkmans/realtime-service:824c280de3844e0014e72fa715f61836fdbdf1ff
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: NODE_ENV
              value: "production"
