apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-service
  labels:
    app: realtime-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: realtime-service
  template:
    metadata:
      labels:
        app: realtime-service
    spec:
      containers:
        - name: realtime-service
          image: dinetimeacr.azurecr.io/realtime-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
